### ISSUE TITLE
Add SkipLast method

### ISSUE THREAD

**Issue by jreina** [jreina/ShittyLINQ.js#24]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.skiplast?view=netcore-2.1

**Comment by bencoullie** [comment]
What is this mean to do? The docs are pretty sparse here. Does it mean remove last item from array?

**Comment by jreina** [comment]
That is odd. `SkipLast` should return all but the last `n` items from an array. So `[1, 2, 3, 4, 5].SkipLast(2)` should yield `[1, 2, 3]`.

**Comment by PieceMaker** [comment]
I'll add this one.
