### ISSUE TITLE
Add Sum method

### ISSUE THREAD

**Issue by jreina** [jreina/ShittyLINQ.js#26]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum?view=netcore-2.1

**Comment by Jayadev6191** [comment]
I will take this one!

**Comment by jreina** [comment]
The `Sum<T>((x: T) => number): number` overload still needs to be implemented here.

**Comment by PieceMaker** [comment]
I'll try my hand at the overload.
