### ISSUE TITLE
Add Count method

### ISSUE THREAD

**Issue by jreina** [jreina/ShittyLINQ.js#7]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.count?view=netcore-2.1

**Comment by estevanjantsk** [comment]
I get this one =)

**Comment by jreina** [comment]
This still needs the `Count<T>((x: T) => boolean): number` overload implemented.

**Comment by PieceMaker** [comment]
It looks to me like the `Count<T>((x: T) => boolean): number` overload was added with #51. I think this issue can be closed.
